const wireCollections = [
  'dbcfeag cgaed fe bfgad aefcdb efa efgda gcef dcaebg dfeagc',
  'ea bfecadg bgafcd deac ebcag eab debfag eabgdc bcgfe bagdc',
  'fbgdec cbgeaf cbfag bd bgda cgbfda dbf fecda bfadc cbedagf',
  'geabdf cfbge dcbeaf aebdf dgea acdgfbe fag gfbea ag cabdfg',
  'gcae cefdg abdcgfe cg fcg afcegd dbgfea agdfe dcafbg bcdef',
  'efgcb fbac dbefg bce efacg fbgcdae cb egfbca dgfaec dcgbea',
  'efcgdb da bdefg dfegba fbacg gbcdea dbafceg adb feda fadgb',
  'ca fcabegd facd agbed acg cfadeg acdeg agcefb cdfgeb efcdg',
  'fdacgb cfa cfage gabce dfagce edagfb dcbfeag fc fced gfdae',
  'acgdbf faedcbg fa cbgdae fgbdae aedbg adf fbea cfdge fedga',
  'ged cadgf gcdafeb cabgfd cgedf aedc ebfcg faebgd ed fcadeg',
  'bcedga dceba gcadfbe dfec adcbfe fda fabge df fbdae bcfgda',
  'fgcabde edbcfg efcdga dfbcea dbaeg fea fa dbaef acfb dbfec',
  'cfbd gefad dce fdeac dc ecabfd dgabce gabdecf afbce fagceb',
  'acfgde egdfb dcaf gecfd ecdbgfa gcdbae cefgba dcg gcefa cd',
  'cadfgb edcgbfa dc cgd fegcb dfabg cdaebg dafc fcbdg gbdeaf',
  'deafg ebafdcg gcdfba bge eb fgcbd gbefac bdce fdebg gdcfeb',
  'acbdef bg agebdf afbcg fgbeca edafcgb eacfb gba ebgc fgcad',
  'ga agc bdegcaf gefbc cfdea dafgec fagce dgebca aefbdc gdfa',
  'abdg ad egcabf ebagf afd gdfceab dcebf dagbef cdgafe deabf',
  'efbadc cafbd eba fegda fcbe dbefa efcbdag adbcge badfcg be',
  'adegb cgafb badgcfe fged fgaebd eabgf bceafd eaf eacbdg fe',
  'dbfega befag gbfdec gacfed fcgdabe bgf deagf bf dafb bceag',
  'fecagd cbfeagd fdecb fg fgbde ebgda cagdbe fge gfab agefdb',
  'ab agdcfe dcfgb cba adefcb adfbc bdae ebacgf aegbdcf fcade',
  'bcfae ebd gefdacb fdceg dbaegc gdbf gcefbd cedfb adfgce bd',
  'gbcafde cdaef dfe ecbf egcda fadgcb bfdac dacfbe bgefda ef',
  'fe cfedab dcfgeb gdbef gadeb cegf fgcbd fbe abdcgf ebacgfd',
  'ad cbfeda acegfb gdcaeb adcgfbe bda abefc dcabf fgcdb afde',
  'acegb efcgab edcfgab aebdc gce ge fage egcdfb agfbc cbdfga',
  'bcaf agefdc bcegaf eaf bdgfe agfdecb efgab af abegc dgacbe',
  'edabcf bdeg gd cadebg dgcab gfcaed febdgca cdg beacd cagbf',
  'gadfeb ag gfda cbeda fbeacg bgdcaef dgfeb eag gbdea fegcbd',
  'efbcda cgfd dgefac dfcgbae degaf adg debacg aedcf gd aebgf',
  'bdc cdfgb cabgf gabd fdebagc eabgcf bd abdcef gfcabd fgedc',
  'dfagbec ceg egfad fdeabg acedg afedcg gc bcgaef eacdb fdcg',
  'gfb egfba eadcfb gf adfg dgebfa dacfegb eagcb cbedgf fadeb',
  'fec caegd efgb cgaedfb gfbdec gfdbc ef cfdgab fdcge fbaedc',
  'gefdba abcef ead gedcab ad bfdecg cbged ebcad cafbdeg cadg',
  'cabg adgefbc cb ebafg febgc fbc gdcfe cafedb egfabc aebdgf',
  'acged febgd agdcfb bdceg gdbecf bc bgc cfeb cfgbaed bgefad',
  'gab adgcbef cebfg abdce dcbefg bafdgc abefgc aegf ag cgbea',
  'fa baf cadfbge dbgef ebacgd dfceba adbec fdeba cfae dacgfb',
  'fgeca gecadfb aecdfb fb gcbed dfgb cgdbea ecfgb gfbdec efb',
  'fg aefgd bafcde gcfe bdgae gfa fedca cagdfb cfaedg ebgacfd',
  'afbcge debgc cafdbg ae eadf afdgb gbdeaf aeb cgfebad abgde',
  'fbc afcegb fadgc fbeda cbed ecdafb cfdab cb fegdcab bdaefg',
  'fegbcd abcf gfabedc bgcad gfacd gedab efdagc dfgcab cdb bc',
  'gfca gbdef eadcfg ebdcag dcg afecd gc decafbg fcegd bcfade',
  'gdae ad gecfd dcfaeb dfegcb gdcaf fdacge adf agbcf cebfgad',
  'ceg febgdca bfgdea gc adcfge cefbag agdc edfcb dfgce gadef',
  'dabegcf bcdfag gdecb gdbeca gaebd fbdce bdagef cg bgc ecag',
  'dacefb efc gfaebc gbfe egcda agfbdc beadfcg fe fbcga cgafe',
  'cbgae faedbg fegab agc ebdgc eacf bgeafc ca cgdbafe gadcbf',
  'dcf dacbg bdcaef dfeacg gacfe cdfag fgde faecgb daebcgf df',
  'egdfa dfaec gdab ga agf dbefga dgebf afbgecd bgafec bgefcd',
  'cfd edafbc afbd cadbeg fgecbad gcaef dacef df dbcae efcdgb',
  'cbag gc cdgbe defbg agebdfc becda dbgcae cdg efacbd fecgad',
  'bf dacgf dfb befc fbedcg gebdc dbacefg abdegf gcdfb bedacg',
  'aebgfdc gadcf gcdfeb dagce agdeb acfe bgacdf dec gfecad ec',
  'befdgca dgcbf fedagc be bfe dcefb ecfdba acfed ebca ebgfda',
  'bfa bdagfc dbega bfgea eagfdb dbgace bcefg dcbgeaf fa defa',
  'agcdeb cgf agbdcef bgdfe efac cgefb abefgc cagdbf fc gebca',
  'adbfce agebd eadcbfg ega abedf fgab dgebc dgfcea ag agdebf',
  'gcebfd feacdbg acegfb afgce gbac geb cdaefg daefb gb fgbae',
  'gadbfc ebgad dgecba fgae eacgdbf af ebcfd afd bdeaf gadefb',
  'bfeacd edgcabf dg gcabd cdaeb acfgb bcgdae dgae cgd bgfdec',
  'cdage dgabec cbadg ge acfde edg becfagd gbec adbcgf fbeadg',
  'ab gbaf cdegba fceadbg gfbecd bca eadcf fgeabc becfa cebfg',
  'afdec bcaefg ca abcd efcdg aec aebdf cdafbe begdaf eadgbfc',
  'faebd fed df bgdcaef cbdega gdbeaf fbecgd badge afebc fadg',
  'abdgf efg fe gdeabf cdbge cfadeg gdbef cafgdeb fbea bgcadf',
  'agdfe cfbd dgfca cd abgfc cdgbea gbecfa gbadcef cda dfgbac',
  'acdb bdcega dbfcge aedfgb dec fcega dc adegc fgceabd gaedb',
  'abe ab dbecfag adgec agbf eadbg cbeafd fbcegd gadbfe bfgde',
  'dgfceba egbcaf fgc bfgdca cbgfe cg faebc agce gdfeb debcaf',
  'bdfac dcfeb dbcefa dbgcaef fbae egdcb fgaecd fec cdbafg ef',
  'gfca dbcaf bfcgd fcgdeab degcb abcedf cbagfd gfb fg fdgabe',
  'efcagd dbag fgd defgacb aebfg dbgfe bdeafg edfbc gd fgecab',
  'efcbg bacfe gbdce fge acegbdf cgdf aebdfg dgbcae ebcdgf gf',
  'fgdeb dcbfg fgae fbeagd edbfa aegdbc egb gafecdb bfdeca eg',
  'bdcaf gdafc cbf bdefa cb fgceda bdfagc fcbgde afcgedb cbga',
  'cfebgd cedgfa dcfabge dbfgc dgeb ge fcegb gfe abfdcg fecab',
  'aeb ab gebfd abcdef edcag cdegaf gaedbc bgfecda debag gbac',
  'ab gebfadc acfge edafbc abegc dcegab gbecfd gbda cab ebcdg',
  'gaedb ebcd fgcea cba dcgafb febadg egcab adcbge efgadcb cb',
  'ca dgfceb bfeacd fcbgd bdgca cfag gaedb abc fcbagd fgecadb',
  'gade gafcb bfgecd bge ecbda gdcbea eg beacg fdaecb agfbecd',
  'eac cdbef ac gfdae dagc afcedgb dcfae dafcge dbfega caebfg',
  'dbagfc bgedca df afgec daf beagdfc aefcbd bedac acfed dbfe',
  'fdacb baedc acedfb bacedg fd gfcab ecdf daf fedgba befgdac',
  'efdgc dfecga adfbe ac cage adc gfbdec cagbfd efdabgc caefd',
  'ca acgf cadbgfe egfcab gefab cea defbc fecab edbcga fbgdae',
  'bcedfa agecd ebgf fcbdg fde cgfed acgbfd cagfdeb ef cgbdef',
  'bfcdea ga fbdegac gecdf cfdab bcgadf facdg aegbcd gac afgb',
  'fdcae afeg fa bceda dfebcga afcgdb dgecf acf fgceda cbfdeg',
  'efgbcd cf bdgace fgbad dfc fceabd dbaegfc bdcgf becdg gfce',
  'efcba ebdfga fda gdefbc da facde dacg fgedc gfeabcd acdefg',
  'daegb cbge bgcaed afgced ge cdabe fdbcaeg fcbeda bgfda eag',
  'cefda fadg bfedac bedfacg dgecfa eag ga fegcb becagd gcefa',
  'dcfe gbeafd df bdcaf ebfcag fcedagb cdbag dcfaeb eabcf fbd',
  'efgbc agbd gd eadgcf becdfa bdace dge debgc adecgb bfdgcae',
  'cdbf edbfgc feadg cd ced gaecdb degfc efcgb fcbgaed befcga',
  'ae caegfd eadgc fedgba fecgd gbacd efac aed afcbged cgdbef',
  'fc afcge dbgecf adcgfe eafbg gdebacf eagcd gfc aecdgb afcd',
  'aedcg gfd cafgebd fg eadbgc adfcb cefg gabefd dacfg efcgda',
  'bfgaed facedb fbec dbgca cagfbde egcfda efdac acbfd fbd fb',
  'fac dcae fgbda fagbce bdfac cbdfe ca cadbfe aegcdfb cebdfg',
  'geabcfd gfcaeb gcbead eba facbg fdgcab ea bgafe fdgbe caef',
  'gcfdeb ceg fabcge edbag fcabdg bcgaf ceaf ec agefbdc cbega',
  'cf adgef cfgbaed bfdc gfc egcdfb dcgaeb degbc fcedg ecagfb',
  'bc afgcb cfdga dfcb cbdgea bgc efcgdab cfedga beafg bagcfd',
  'egdfb fa agfbe eacf befagc fba fbedacg cadebg agcbe cfgbda',
  'acgbde acgdbef cba ca bcgfd cade egdafb aebgfc agbed adgcb',
  'egbac efacgd gfbd fbcdag fecbad dgc badcf gfcebda dbcag dg',
  'adgcf fbgcda efcgda dcbea fedg cfebag fae ef acdef gecbfda',
  'fegdba ba cedgaf gbade bfad egfda gba cadbgef gbced fcaegb',
  'gbacef gdab defgc bagfdc dfb afgcb efdbac bd dfbcg befcgad',
  'fgacd ef dagfce ecdfa fae adfbgc cegf febdga ceabd bgacedf',
  'fbgdc afedg gcbafd gfedbc cfdag acd fbdeacg acbfde cgab ac',
  'becf feadb abfedc dfcageb gcbda bafedg aec daecfg acdbe ec',
  'dc cbfegda bfeadg dbcg gabfd adc dbcfga bface fgcade fdabc',
  'bc bfgedc fbc adfbceg cegb degcf eabdf defcb cdfgae fcagbd',
  'ge cabgd egca egd adgbecf bfdagc decbag agbde deafb ebdgfc',
  'cg cfagbd gcedfa efdbc gcd gbefda fegad efdcg caegdbf agce',
  'bfedgc bec ce fcaebd efabg gdec cgfdb aebdfcg bfgcda cgbfe',
  'db dfcbge edgfca gabd dcb agfcd bafcd afbgcd ebafc edgfbca',
  'cadegbf egdfbc adc acbdg dgbcf adgfbc da cgfdae fbda ebcga',
  'geacf abc gfedba cbadfg dbcg gfdba cagfb cb bfdcae adfecbg',
  'abdfcge adbeg badcef egcf fg fgb fbdec gebfd abgfcd gfebdc',
  'facdbe acgfbd dbc bd abgcd adceg bcegfa fdgb bfgca badcfeg',
  'gcda cadbe abcedf cabeg edbgcf begcda begaf cg acbdefg gbc',
  'cgf gf fadegbc afgcde abgced fecba ceagf dcagbf fgde cdaeg',
  'abdef bc gecaf dbcgfae cbfg efcba bac acebfg degcba dcegfa',
  'bfcged bgdac becad fagc aegbdfc gacfdb dbgfc dafgbe ga bga',
  'abcfg baecf agec fcgaeb agedbf ag dacfbeg bag eafcdb fcgdb',
  'ba baf dfbgce cgab cefgdab efcad efacbg cgfeb ebafgd cafeb',
  'cegafd egdcba gbedf cgfde cfad ecf fcegadb eagdc bgaefc cf',
  'gedfa abdce fadbe ebfc fba badgce bf gabefcd fdbgac befcad',
  'bacef cg dgabec agfc edfgb cge agfdbec fcabeg cgebf abfdce',
  'eafgd ce fbgaced ecfga eafdgc gdce cea cefdba cbfag bdgafe',
  'decgabf fecd acd acbegf agdec gabed gacbfd faceg cd fgeadc',
  'egd fdaebg gcbeadf fcdge ge adecf gbce dgfbac dcfgeb gdbcf',
  'ad cbafe dabe dfa gbfcea ceafd dcbagf fabdce bfceadg dfgec',
  'fc cdgbae gfcbad badcg fcdba feadb fac cgefad fdgbeac gfbc',
  'fdgace edac cdfag de dcfge facebgd cgebf dfebag def bafgdc',
  'gedfac acedb fbcadge acgefb dbgf fdaeb dgafe fgaedb bf fba',
  'gefbdca fagbed cgaeb gf ebdfa gdbf afebg feg feadcb geacfd',
  'efadgbc bfag edgcb cga cefab afbegc ga gaebc eafcdb daefgc',
  'efcgbd gebcf gcadbf agfce fcdeagb gfa ageb aefdc ga gacbef',
  'ga adbg fdeac gfa fdgbcae dgfabc cfgdb fegbdc fcabge agcdf',
  'febdc dacfeb gbfce cfgae bge bgdf dgcfbea baecdg gb ecfgbd',
  'bgacfd cdfabeg adgce bcegd acdefg gb cgb bgae ecbadg bdfec',
  'bc gdfeac fbaec egfcba dacbeg cab gacbfde eabfd faceg fgcb',
  'fd dfe fdgae abegfd dbcaeg dfgb caedbf efcag dageb dbfeagc',
  'agefbc aefdb abdge cdef bfdcga dacbf fe gbdcefa eabcdf efb',
  'gbade adecfg abegcdf dcbfa cgbafd cfeb dfaebc fe feabd efa',
  'dfba dfc efbac cgead ecfgab gdfecb edacbf df afced bgecfad',
  'abfcg egacf bceafg dabgc fgb fb fbecadg fbce gafcde gfdbea',
  'caegb decgbfa cebf edacg cgfbae gbc gfbea baedgf bc bfcdag',
  'ad gadf feacg aed agbfce egcda fedcba abcdgef bcdge gecafd',
  'cegbd bgcfda dbfeag acef gcead cagfde dcfga gae fagbced ae',
  'fag edfcg cdfa fa ceagfd fdgabe gebac egbfcd egdcfab gcaef',
  'abe bcdfa acdbgf befd eadbc acbfgde eb fgcaeb gacde fcdbea',
  'afdgce dgabe dgfbe bdegfc dfg agcbdfe fd abegfc dcfb bfgce',
  'dgfcea eagcbd gfceb adgb cgdeb dg eacdbf bedcafg dge abedc',
  'dgecf badfce egcdfab efabd edfca ac badc gbcfae eagdfb caf',
  'gfb bacgde acbdgf afbd bdgca bf bgfdcea ecfag dgfecb fbcag',
  'bcdg dc gedabc dec cdeag cbedaf gfaebc dafge bcegdaf agceb',
  'gc cag agbec dacbe dcbg edcbgaf gdcfae dacebg eabfg febacd',
  'gfdbace edbc ecfgab efcdbg ce fdcabg fedga egc cbdgf gedfc',
  'afceg bgdeaf daceg degacb fe dfec adfgec acdgefb gcbfa gfe',
  'bdca gcfdbea dc acbedf gbfde cagefd cfebag dcf bdcfe ebafc',
  'cabefg adgeb fd dacf afgcb bgefdca decbfg fbd dafgb dfagbc',
  'bacgef defcga afdgebc facebd afebc badc bdfeg dc dbfec dce',
  'cdf decb fagec dc dcgbaf bacfgde gdfeb efbadg efgbdc cfged',
  'faebgd egdfcb gecadb gdbce ag aeg cgeab gacd faecb debcafg',
  'eagc bdegf ga gdaef adg cbgdaf cfaegd dabfce adcegbf dfeac',
  'cfgbe ceadf ab cbefag cegfbd bega egdfcab fba gbfacd efcba',
  'fgdce ecgbaf gebd bfg fdbac dfacge fbegdc cgbdf dacbfeg gb',
  'febda edagf egf gdcf bcgafed fg agcbfe caged gcadeb dgaefc',
  'eabgf fbdcg dfecag acebgf bafdge fbgce ecf eacb begfacd ec',
  'fabgcd febdac acgdf beagc dgaec de eafcdg dcfbeag dae fdge',
  'bcafeg ecbad dcfe ecbgafd gdefab dfabce de cadgb ebd fcaeb',
  'afcgeb gcebf cdbfag cfea bdgfe cbgaf ec gfabecd bedgca egc',
  'ecdafb cfeag bdgaf febga egabfc eb gbec fcebdga eab dfegac',
  'fgbacd fbcedga fgc fg gdaf bcdgef cdfba fabced cgbfa gcabe',
  'dfbcga caefbd ac gaedbfc afgc afgdb bdgce dgcab fdgaeb dca',
  'bdgce dbf cgeadfb fd gfbde dfbecg gaebf dacgfb cdebga dcef',
  'gbda egadbf bfegd acgfde bfgaec gabef cfbde aefdbcg dg ged',
  'afebcd degcfb dce dcfgb degf bdcgafe bdcge gcabdf de cbaeg',
  'eadcfg dfc gcbfade cd edafb fbcge afdbec agdbef ecfbd bdac',
  'agbedf degbfc begcd ceagdf cgabe ecd dcbf ebfdg abecgfd cd',
  'aefdb degf fdbaeg egb agebd bcfage gcedfab bdagc ge febacd',
  'cegfba dfcea gbea bac ebafc gdcebf gebcf ba gfdbac gacfdbe',
  'ec ecfab feadbg ecb dabfc cbfegd dbafgec feabg caefgb ecag',
  'fd decag fagbe beafdg egdacbf gbfcde dbfa agfbec dgf geadf',
  'af eabfdg edabc dgfabc efga fdbae fcagbed abf gbcdfe efgdb',
  'dbfacg degcb gecdaf adcbg bafegcd dfbag gbdefa ac cabf agc',
  'efab cbedg aedfbc bfcad geacfd ea fabdcg adbfgce ade ecabd',
]

const outputs = [
  'fae cfge fae baefdc',
  'cdbagf fagbcd bae fcegb',
  'gecfdb cbfga bacgef dfb',
  'dfeabc dbaefc fdaebc fga',
  'gc caefdg gcf egdcf',
  'fgecb bcfa bc efcag',
  'da ad cgabde cebdga',
  'cdeafg cag efgadc gacbfe',
  'gabdef fdegba gaedcf fac',
  'fad egdcf feab bfcagd',
  'dfgca gabefd dafgc ecfgd',
  'adgcfbe fbgae dgebafc gacedb',
  'aecbfd aedcfb bdaef abfc',
  'bdfc bcgaed bgdace afegd',
  'eadcbg cdfega fdgeac dgc',
  'afdc adcf befdag gfcdb',
  'cbdagf bdce gdfeb fgead',
  'begdaf gcbe ebdfag dabefg',
  'acfedbg bfaecdg gca facedg',
  'bfedc cbedf gdab afd',
  'be agdfe cedbag dcbeaf',
  'bdgeac adgbfe bdgae acfgbed',
  'bdfa cagbe gceba agbdfe',
  'geabcd gdbea ebgafd egdab',
  'gfecda dfabc edab bfcad',
  'gebdcf bd dgfb ebdcgf',
  'dcgafb dfaebg fbec agbdfc',
  'debfg abecfd adbefc gdcbfe',
  'gdcbf cedbaf dbagec becfa',
  'eg cafegb fcbeag acbgef',
  'defbg dgaebc eaf cebga',
  'befadcg fbgca afdecg bgceda',
  'cabefg degbcf gdbef bcdgef',
  'ecfad cgbade aegdcb gfbae',
  'faecdb fgecd cbfdag bcfadg',
  'gcfd eadbc dbegcfa eabcd',
  'edfba afgebd adbegf efcbda',
  'abcdef gcfbd bfegdac gcead',
  'defcgb ade bgecd ceabf',
  'bcdafeg ecbafd adbecf fbcge',
  'dceag efbc cbfdeg ebcdfg',
  'gaceb aegf fgcbe cgebf',
  'dabcef dafcbe acgdbe ecdfab',
  'abcedg bf bf agedcfb',
  'dcfgab dgfea gf cafdgb',
  'deaf cbafge cbegd aedbg',
  'cgfad ecbd edafb cgafd',
  'fbca cdbag cdfgab cgedbfa',
  'gcefd bcdafge cdefg edfgc',
  'dgebafc edfgc da cbgafed',
  'ceg ebdagf agdfe afbgce',
  'dfcabg abfdge gadbe cg',
  'ef fbaedc ef efc',
  'eagfb aebgf gcbfad gfeba',
  'fcd fecadb egacf deabcf',
  'fegbd gdfbe begdfc efcbadg',
  'adbf cabde baegdc cgbeda',
  'fcegabd abgc dacbe cdaebg',
  'bfec feagcbd egdcb daegbf',
  'ceadg edcag fdcga cdbagef',
  'dfbcae bafgdce bgcdf egbdfa',
  'ebcgdaf aecgdbf fgcadb fa',
  'fegbc acfe becga deagbc',
  'gdfcabe ebadf ga bfag',
  'agefb gb adfbe efabd',
  'fa bdgaef gdbacf af',
  'bedac acbed abcdfge dgc',
  'cdbgea cgdaeb cegad gdeac',
  'cagfeb cefabg fcbeg eadcgb',
  'cdfeg afdce edfac gdfabe',
  'dcebfg dgaf fd cdegfba',
  'bgdfe fabe gbfadc gbfcda',
  'cegfba fbcd bfdc dca',
  'badeg bdecgf cd cdageb',
  'ebgfd efdgb gceadbf ba',
  'bedfac edbfg aegc eabcdgf',
  'bdfagc dcfabg gdbfeca eabf',
  'gcaf bfg fbg gf',
  'fbeag ecgfabd degacf debgfac',
  'caefb cbfdage ecfgb bgedc',
  'dgbcea bdaef gfbde dfgbea',
  'gbca fbdca cegfdb fcagd',
  'fge fabec gfbadec bfceg',
  'beacgd bdfeg afgecd gedbf',
  'dagb cegfa bca bac',
  'dfcagb cbed bagce dbce',
  'cgdfab cfag bac cbfegad',
  'dgae bgfca abegc cfdebg',
  'gafceb dbeacgf cdga fbcde',
  'bedca cdaef baecfd befcad',
  'egabcd cedab eabdfg adf',
  'efdab efdgcab ca cedfg',
  'cfeba efdcbag dacebg agefcdb',
  'fgeb bcfdg def ef',
  'cbadfg facdb afbg dfecba',
  'fa bdfcga fcbegd efacd',
  'bcedaf adbegc badgec bgcfd',
  'da bgafde cegfd edafgb',
  'gae egcb egbc egdafcb',
  'dcfea eag cedfa bgfcaed',
  'dfce geacbf cefd ebdacf',
  'bgcfe bedcg abgd gdba',
  'cfabgde fgdcbe efacgb abgcef',
  'ae eacf abdegcf eda',
  'cfg dgeac afbge edgcba',
  'dgeca afgedb cfdga aefgcd',
  'efbc agcdb fagdbe bacdf',
  'cdea cfbdeg ac afdcb',
  'bagef cafgb afbeg cbgaf',
  'bgafc baecgdf bcfged gbdfeac',
  'fdbc cgdbe gdabce gfdce',
  'bc bc cbfadg adcbge',
  'bagfec bcdgaf cbfgad dgcbfa',
  'fdgbc gbadef gfcdbae edfgab',
  'bacdg facbegd cgd dfcgae',
  'fcagd gcadf gcefdba gefabc',
  'gedaf bdega abgde bafd',
  'cdgef bd gbfac ecbgfad',
  'abcgfed gfce fae efacgdb',
  'gdcbf cedfbg dacgf dcafg',
  'abdef fdeacg ace ecbf',
  'dacbgf dc cdfba dc',
  'bcefd gceb fcagde cbfgad',
  'cagdfb bgecda cgedba fabdcg',
  'fgced dgfacb befdagc cefgda',
  'agebf bgdcfe ec agcbdf',
  'acfdg cbdfa afceb gbda',
  'dgacb bagdc fgcbd aegbc',
  'cb eadfgb bcfag dgcb',
  'cbeadgf cfdbag gfdbe gf',
  'ceafdb bfcag dcgba bgdf',
  'dbace gdbeac dacfgbe abdce',
  'gdebacf gf gdfe cfega',
  'bcfadeg afceb edfgac gcabed',
  'fgdecab abdcg cefabdg egdbfa',
  'bcdfea efdabg ga fdbgc',
  'fdcegb abf baf ecabf',
  'bfged defgb gbfed efc',
  'bcdgaf fdbgca bfa fgbdca',
  'decfbga cagf adcgbe dgefb',
  'eadfbg dgec efgca degfa',
  'dc dcafge abecgf dc',
  'fdcae gfdbea bdfcg eg',
  'cebaf aecbgdf cgdbfa fbaec',
  'cf cfabd caf gdfcea',
  'fdgac gacfbed edgacf dgcfa',
  'fb bf bf agefcd',
  'egf fedab gaefb eagbf',
  'ga acg gcfbade dgecb',
  'gcebaf geba acfde fga',
  'adbcfg efadc agcdf cgdbf',
  'gb fcedb becdf gb',
  'adcbfg gdfcea deafbcg ceadfg',
  'afbegc cdgabe bagecf ebcdga',
  'dgfb gaedbf gfbd dgfcabe',
  'cdbefa adfcbg fecagdb ebf',
  'dbcfea bcfe fecb bafde',
  'afdce bcfegd efgbac adgce',
  'abdgc defagb cbef egcaf',
  'agebc bgcae cbg gefba',
  'gedfca ad febgac dcaebf',
  'defgab dacgf cebdg gecdfa',
  'acebg fag fgdec dfegcb',
  'eadbc afdgbc bgaefc cabfdeg',
  'debag bedgf ebdcfg cgebafd',
  'ecbgf dg dbfcgea ebcad',
  'feadc febad dacef caf',
  'fbgdcae gdfbca fbg fgaec',
  'dfage bcefad cfbage fdgae',
  'gc cbdg gc fedcba',
  'ecdb edgfbc eagcfb cdafbg',
  'efg gcfea dcfe fcgea',
  'eafbc bcfage defcb agcbfe',
  'gbfca cbeagf cfbgad fbd',
  'adbc eafdcb dabc fgedb',
  'ecgfa efgbd fedgab dc',
  'ag fdeabg decbg ag',
  'acedfg agd cega bgefd',
  'ceafbg abf ecfba ba',
  'aebcgfd cdabf ebdg egdcaf',
  'cegbad gcdf gaedc ebdgca',
  'fbgea gcefb fegcad decfag',
  'fcdgea ceadg fegd bdcaef',
  'bed bgeafd fgeacb ecdfba',
  'gce dacfbg cebfg afec',
  'bea gbafd eab befdac',
  'egcadfb adgf gbcefd gcf',
  'afbgd cagf adc bfedga',
  'fegbd fgbde bgfde fcegbd',
  'abgefd gdefba deg gfeba',
  'de bagec gcdeb ebagc',
  'efdab agefdc befad defabc',
  'fdebg fdgbe cdgeb bagdef',
  'bgfdae fdge acfdeb deafb',
  'febac aefcb cbfgda cafed',
  'acbefg afbeg fecgabd bcfad',
  'bfda befgcda fgd adfb',
  'gefa gfabcd fba gcdfab',
  'bcadg afbc bdgfa abcdg',
  'fdceba bfceda ecgdfa aefcdg',
]

export { wireCollections, outputs }
